### ISSUE TITLE
[REQUEST] Allow changing title template

### ISSUE THREAD

**Issue by rEnr3n** [krathalan/wtwitch#12]
**Is your feature request related to a problem? Please describe.**
When I watch a stream using `wtwitch w`, the title I see is something like "Watching `INSERTUSERNAME` on Twitch".

**Describe the solution you'd like**
I'd like to use the title template I have set on streamlink instead of wtwitch overriding it.

**Comment by michaeldxyz** [comment]
You have `title=SOMETEXT` in the streamlink config file?

**Comment by rEnr3n** [comment]
Mine is `title={title} - {author} [{category}]`

**Comment by michaeldxyz** [comment]
Looks good! I like that the info is right there in the window title.
