### ISSUE TITLE
[BUG] cache_online_subscription_json fails, when the Twitch API returns a 401 "Invalid OAuth Token"

### ISSUE THREAD

**Issue by the-metalgamer** [krathalan/wtwitch#20]
**Describe the bug**
Sometimes when I use wtwitch check I get the following jq error:

`jq: error (at <stdin>:1): Cannot iterate over null (null)`

Enabling the debug mode via the environment variable, I see that the twitch API return a 401 "Invalid OAuth Token", see debug output at the end.

**To Reproduce**
wtwitch c

**Expected behavior**
In this case, I think wtwitch should automatically generate new OAuth tokens.

**Logs/system info (please complete the following information):**
 - OS: Arch Linux
 - `wtwitch` version: 2.6.1

You can also include a debug log (this is very helpful!). To do so:

[wtwitch debug log](https://gist.github.com/the-metalgamer/dd663025f600317960f6fe47d95a03a9)

**Comment by krathalan** [comment]
I attempted a fix for this issue in ed9170a. Please reopen this issue if the problem persists!
