### ISSUE TITLE
[BUG] subscribing to a substring of an already subscribed channel fails

### ISSUE THREAD

**Issue by rengelmann** [krathalan/wtwitch#21]
**Describe the bug**
When subscribed to a channel name $string1$string2 and subsequently subscribing to $string1 the error "you already subscribed to $string1" appears

**To Reproduce**
wtwitch s $string1$string2
  Subscribed to $string1$string2
wtwitch s $string1
  Error: You are already subscribed to $string1

**Expected behavior**
Should be able to subscribe to names of channels which happen to be substrings of existing channels

**Logs/system info (please complete the following information):**
 - OS: macos
 - `wtwitch` version: 2.5.0

**Comment by krathalan** [comment]
This should be fixed via c0d58a1 in version 2.6.2. Please reopen this issue if the problem persists.
